os: linux
language: minimal

addons:
  apt:
    packages:
      # Install dependency to use `xmllint`
      - libxml2-utils

jobs:
  include:
   - name: XML Validation
     script:
       # `xmllint` doesn't work over https, we need to download the xsd files first
       - wget https://raw.githubusercontent.com/Cockatrice/Cockatrice/master/doc/carddatabase_v3/cards.xsd -o cards-v3.xsd
       - wget https://raw.githubusercontent.com/Cockatrice/Cockatrice/master/doc/carddatabase_v4/cards.xsd -o cards-v4.xsd
       # Then we can link the xsd file locally
       - xmllint challenge_tokens.xml --schema cards-v3.xsd --noout
       - xmllint tokens.xml --schema cards-v4.xsd --noout
