os: linux
language: minimal

addons:
  apt:
    packages:
      # Install dependency to use `xmllint`
      - libxml2-utils

jobs:
  include:
   - name: XML Validation
     script:
       # `xmllint` doesn't work over https, we need to download the xsd file first
       - wget https://raw.githubusercontent.com/Cockatrice/Cockatrice/master/doc/carddatabase_v4/cards.xsd
       # Then we can link the xsd file locally
       - xmllint --schema cards.xsd tokens.xml --debug

# --noout oder debug

#wget https://apps.nextcloud.com/schema/apps/info.xsd
#xmllint appinfo/info.xml --schema info.xsd --noout
#rm info.xsd
