os: linux
language: minimal

addons:
  apt:
    packages:
      - libxml2-utils    # Needed for `xmllint`

jobs:
  include:
   - name: XML Validation
     script:
       # xmllint doesn't work with https, we need to download the xsd file first
       - wget https://raw.githubusercontent.com/Cockatrice/Cockatrice/master/doc/carddatabase_v4/cards.xsd
       # then we can link the xsd file locally
       - xmllint --schema cards.xsd tokens.xml --noout

#xmllint --format --pretty 1 --load-trace --debug --schema https://raw.githubusercontent.com/Cockatrice/Cockatrice/master/doc/carddatabase_v4/cards.xsd /tokens.xml

#wget https://apps.nextcloud.com/schema/apps/info.xsd
#xmllint appinfo/info.xml --schema info.xsd --noout
#rm info.xsd
