os: linux
language: minimal

addons:
  apt:
    packages:
      # Install dependency to use `xmllint`
      - libxml2-utils

jobs:
  include:
   - name: XML Validation
     script:
       # `xmllint` doesn't work over https, we need to download the xsd files first
       - wget https://raw.githubusercontent.com/Cockatrice/Cockatrice/master/doc/carddatabase_v3/cards.xsd -O carddb-v3.xsd
       - wget https://raw.githubusercontent.com/Cockatrice/Cockatrice/master/doc/carddatabase_v4/cards.xsd -O carddb-v4.xsd
       # Link downloaded xsd files locally
       - xmllint --schema carddb-v3.xsd --noout challenge_tokens.xml
       - xmllint --schema carddb-v4.xsd --noout tokens.xml
       
